---
- hosts: rdnsmaster
  user: vinod
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
       - /etc/ansible/roles/rdnsmaster/inputs/inputsrdns.yml
  any_errors_fatal: true
  tasks:
  roles:

   - dependencies
   - rdnsmaster
